function about_menu_callback(obj)
%ABOUT_MENU_CALLBACK Displays the about dialog box


msg = {'FitIt',...
       ['version ' obj.version],...
       '',...
       'Otto Virtanen',...
       'virtanen@pc.rwth-aachen.de',... 
       '',...
       'Copyright RWTH Aachen University'};

msgbox(msg);


end

