function [psize,dcoeff,bool] = read_ns_file(filename, startRow, endRow)
%READ_NS_FILE Import numeric data from a NanoSight .csv file as column vectors.
%   [psize,dcoeff,bool] = read_ns_file(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [psize,dcoeff,bool] = read_ns_file(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [psize,dcoeff,bool]
%   = read_ns_file('Run1-001-alltracks.csv',2, 554765);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/03/15 08:39:39

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
%ParticleID = dataArray{:, 1};
psize = dataArray{:, 2};
dcoeff = dataArray{:, 3};
%Frame = dataArray{:, 4};
%Xpixels = dataArray{:, 5};
%Ypixels = dataArray{:, 6};
%NormalisedintensityAU = dataArray{:, 7};

% convert 'True' or 'False' to 1 or 0
f = @(x) strcmp('True',x);
bool = f(dataArray{:, 8});

