function set_fit(obj,p)
%SET_FIT Recalculates fit with parameters p
%   
% set_fit(p)
%
% Parameters
% p             Parameter vector with structure: 
%                  dr          Decay rate          p(1)
%                  epds        Max pd of skin      p(2)
%                  fuzz        Fuzziness           p(3)
%                  amplitude   Amplitude           p(4)
%                  Burr a      Burr parameter      p(5)
%                  Burr c      Burr parameter c    p(6)
%                  Burr k      Burr parameter k    p(7)

[obj.fit,...,
 obj.rpd,...
 obj.rpsd,...
 obj.psd] = obj.scattered_intensity(obj.qfit,...
                                    p(4),...
                                    obj.nc,...
                                    p(1),...
                                    p(2),...
                                    p(3),...
                                    p(5),...
                                    p(6),...
                                    p(7));


end

