function display_about_box(obj)
%DISPLAY_ABOUT_BOX Displays the about dialog box

% Copyright (c) 2015, Otto Virtanen
% All rights reserved.

msg = {'FitIt!',...
       ['Version ' num2str(obj.version)],...
       '',...
       'Written by',...
       'Otto Virtanen',...
       'oljvirtanen@gmail.com',... 
       '',...
       'Copyright (c) 2015, Otto Virtanen',...
       'All rights reserved.'};

msgbox(msg);


end

